services:
  mysql:
    image: mysql:8.0
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: laravel
      MYSQL_USER: laravel
      MYSQL_PASSWORD: secret
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - 3306:3306

  php:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    volumes:
    - ./laravel:/var/www
    environment:
      DB_HOST: mysql
    depends_on:
    - mysql

  nginx:
    image: nginx:latest
    ports:
      - 80:80
    volumes:
      - ./laravel:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php

  queue:
    build:
      context: .
      dockerfile: docker/php/Dockerfile
    working_dir: /var/www
    command: php artisan queue:work
    volumes:
      - ./laravel:/var/www
    depends_on:
      - php
      - mysql

  nextjs:
    image: node:18-alpine
    working_dir: /app
    volumes:
      - ./nextjs:/app
    ports:
      - 3000:3000
    command: sh -c "npm install && npm run dev"

volumes:
  mysql-data:
